---
title: "Benefit of `{usahex}`"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
    %\VignetteIndexEntry{Add Other Data}
    %\VignetteEncoding{UTF-8}
    %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



```{r setup, warning = FALSE, message = FALSE}
library(usahex) 
library(sf)
library(tidyverse)
require(patchwork)
```



https://r-graph-gallery.com/hexbin-map


Download the Hexagon boundaries at geojson format here: https://team.carto.com/u/andrew/tables/andrew.us_states_hexgrid/public/map


```{r import-data}
sf_usahex <- usahex::statesDC
sf_other <- read_sf("../data-raw/us_states_hexgrid.geojson") |> 
  mutate(google_name = gsub(" \\(United States\\)", "", google_name))
```


```{r, onelabel-other, out.width="100%", fig.height = 5, fig.width = 10}
ggplot(sf_other) + 
  geom_sf() +
  geom_sf_text(aes(label = iso3166_2)) + 
  labs(title = "Other data source") + 
  theme_void()
```


```{r onelabel-usahex, out.width="100%", fig.height = 5, fig.width = 10}
ggplot(sf_usahex) + 
  geom_sf() + 
  geom_sf_text(aes(label = abbr_usps)) + 
  labs(title = "{usahex}") + 
  theme_void()
```




```{r twolabel-other, out.width="100%", fig.height = 5, fig.width = 10}
ggplot(sf_other) + 
  geom_sf() +
  geom_sf_text(
    data = mutate(sf_other, geometry = geometry + c(0, 0.5)) |> sf::st_set_crs(4326),  
    aes(label = iso3166_2), 
    fontface = "bold", 
    size = 3.25
  ) + 
  geom_sf_text(
    label = "Line item 1\nLine Item 2", 
    size = 2, 
    vjust = 1
  ) + 
  labs(title = "Other data source") + 
  theme_void()
```


```{r twolabel-usahex, out.width="100%", fig.height = 5, fig.width = 10}
ggplot(sf_usahex) + 
  geom_sf() + 
  geom_sf_text(
    data=mutate(sf_usahex, geometry=geometry+c(0, 5)), 
    aes(label=abbr_usps), 
    fontface="bold", 
    size=3.25
  ) + 
  geom_sf_text(
    label = "Line item 1\nLine Item 2", 
    size=2, 
    vjust = 1
  ) + 
  labs(title = "{usahex}") + 
  theme_void()
```


```{r}
ggplot(sf_usahex) + 
  geom_sf() + 
  geom_sf_text(
    data=mutate(usahex::statesDC_labels, geometry=geometry+c(0, 5)), 
    aes(label=abbr_usps), 
    fontface="bold", 
    size=3.25
  ) + 
  geom_sf_text(
    label = "Line item 1\nLine Item 2", 
    size=2, 
    vjust = 1
  ) + 
  labs(title = "{usahex}") + 
  theme_void()
```





